include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_print: true

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  exclude:
    - lib/l10n/app_localizations*.dart
